name: Publish Python Package to Test PyPI

on:
  push:
    tags:
      - 'v*-test'


permissions:
  id-token: write
  contents: read   # Allows reading the repository contents

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
        pip install -r ai-speech-realtime-sdk-python/dev-requirements.txt

    - name: Run Unit Tests
      env:
        PYTHONPATH: ./ai-speech-realtime-sdk-python/src
      run: |
        pytest ai-speech-realtime-sdk-python/tests/ --disable-warnings
    
        
    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" | sed 's/-test//' >> $GITHUB_ENV
    
    #Build using the version in the tag
    - name: Build the package
      env:
        PKG_VERSION: ${{ env.VERSION }}
      run: |
        echo "VERSION=${{ env.VERSION }}"
        python -m build

    - name: Publish to TestPyPI
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      
        #env:
      #  name: testpypi
      #  url: https://test.pypi.org/p/oci-ai-speech-realtime/  # Replace <package-name> with your PyPI project name
